# Generated by Django 4.2.7 on 2026-05-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAplicativo',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=80)),
                ('modulo', models.CharField(max_length=80)),
                ('entidad', models.CharField(max_length=80)),
                ('entidad_id', models.PositiveIntegerField(blank=True, null=True)),
                ('usuario_nombre', models.CharField(blank=True, default='', max_length=150)),
                ('usuario_email', models.CharField(blank=True, default='', max_length=150)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('fecha_evento', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'logs_aplicativo',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
