sonar.projectKey=SkillHub
sonar.projectName=SkillHub - Sistema de Intercambio de Habilidades
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=venv/**,staticfiles/**,**/__pycache__/**,**/migrations/**

sonar.language=py
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token= sqp_f7096e8a7cb984977914c7f82c3ae09b33ed90a1