# Generated by Django 4.2.7 on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidad',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='disponibilidad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
